recipes:
- ingredients:
  - [Meyer's Silver Rum, 1.0, oz]
  - [Appleton's Gold Rum, 0.5, oz]
  - [Lime Juice, 0.333, oz]
  - [Passion Fruit Syrup, 0.7500000000000001, oz]
  - [Sugar Syrup, 0.5, oz]
  - [Angostura Bitters, 1.0, dash]
  name: Beachcomber's Gold
  type: Tiki Drinks
- ingredients:
  - [Orange Juice, 3.0000000000000004, oz]
  - [Lemon Juice, 2.0, oz]
  - [Sugar Syrup, 1.0, oz]
  - [Passion Fruit Syrup, 1.0, oz]
  - [Meyer's Dark Rum, 1.5000000000000002, oz]
  - [Meyer's Silver Rum, 1.5000000000000002, oz]
  name: Chief Lapu Lapu
  type: Tiki Drinks
- ingredients:
  - [Lemon Juice, 2.0, oz]
  - [Passion Fruit Syrup, 2.0, oz]
  - [Meyer's Dark Rum, 4.0, oz]
  name: Hurricane
  type: Tiki Drinks
- ingredients:
  - [Orange Juice, 6.000000000000001, oz]
  name: Orange Juice
  type: Juices
- ingredients:
  - [Pineapple Juice, 6.000000000000001, oz]
  name: Pineapple Juice
  type: Juices
- ingredients:
  - [Orange Juice, 3.0000000000000004, oz]
  - [Pineapple Juice, 3.0000000000000004, oz]
  name: Pineapple Orange Juice
  type: Juices
- ingredients:
  - [Lime Juice, 0.7500000000000001, oz]
  - [Sugar Syrup, 1.0, oz]
  - [Meyer's Dark Rum, 3.0000000000000004, oz]
  - [Angostura Bitters, 2.0, dash]
  name: Planter's Punch
  type: Tiki Drinks
- ingredients:
  - [Lime Juice, 1.0, oz]
  - [Grenadine, 1.0, oz]
  - [Appleton's Gold Rum, 1.0, oz]
  - [Meyer's Dark Rum, 1.0, oz]
  name: Shrunken Skull
  type: Tiki Drinks
- ingredients:
  - [Meyer's Silver Rum, 2.0, oz]
  - [Orange Juice, 2.0, oz]
  - [Grenadine, 0.5, oz]
  name: Sunset Rose
  type: Cocktails
- ingredients:
  - [Appleton's Gold Rum, 0.5, oz]
  - [Meyer's Silver Rum, 0.5, oz]
  - [Lemonheart 151 Rum, 0.5, oz]
  - [Lime Juice, 0.5, oz]
  - [Pineapple Juice, 0.5, oz]
  - [Sugar Syrup, 0.5, oz]
  name: Tiger Shark
  type: Tiki Drinks
- ingredients:
  - [Lemon Juice, 1.0, oz]
  - [Pineapple Juice, 1.0, oz]
  - [Passion Fruit Syrup, 1.0, oz]
  - [Meyer's Dark Rum, 2.0, oz]
  - [Angostura Bitters, 1.0, dash]
  name: Trader Vic Grog
  type: Tiki Drinks
- ingredients:
  - [Orange Juice, 2.0, oz]
  - [Lime Juice, 2.0, oz]
  - [Pineapple Juice, 2.0, oz]
  - [Grenadine, 0.5, oz]
  name: Tropical Punch
  type: Juices
- ingredients:
  - [Lime Juice, 1.0, oz]
  - [Lemon Juice, 1.0, oz]
  - [Pineapple Juice, 1.0, oz]
  - [Passion Fruit Syrup, 1.0, oz]
  - [Meyer's Silver Rum, 1.0, oz]
  - [Appleton's Gold Rum, 1.0, oz]
  - [Lemonheart 151 Rum, 1.0, oz]
  - [Sugar Syrup, 1.0, tsp]
  - [Angostura Bitters, 1.0, dash]
  name: Zombie
  type: Tiki Drinks
type_icons: {Cocktails: CocktailsIcon.gif, Juices: JuicesIcon.gif, Tiki Drinks: TikiDrinkIcon.gif}
